### ISSUE TITLE
Upgrade link in side nav doesn't link to anything.

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs-app#56] opened 2017-12-29 14:23 UTC
###### Copied from https://github.com/phalcon/docs/issues/1425
The Upgrade link in the side nav under General is not an anchor tag and does not link to anything.

**Comment by sergeyklay** [comment] 2018-05-07 07:04
@niden Could you please take a look?

**Comment by diplopito** [comment] 2019-01-28 20:19
With @ruudboon we found that the problem stems from the MD to Html conversion: the hashtag link to the anchor is being replaced by a slash, which breaks the link. In the case of https://docs.phalconphp.com/3.4/en/application-micro, in the "Method - verbs," the issue is that the links on the nav are in plural but the anchor is in singular.

**Comment by ruudboon** [comment] 2019-02-01 17:01
Closing the issue. This is handled in one of the deployments last week.

**Closed by ruudboon** 2019-02-01 17:01 UTC
Labels: bug
